version: '3' # specify docker-compose version

# Define the services/containers to be run
services:
  angular: # name of the first service
    build: frontend # specify the directory of the Dockerfile
    ports:
      - "8888:80" # specify port forewarding

  express: #name of the second service
    build: backend # specify the directory of the Dockerfile
    ports:
      - "3000:3000" #specify ports forewarding